simplesocial/accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup')
]

simplesocial/posts/urls.py
from django.urls import path, include, re_path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    re_path('by/(?P<username>[-\w]+)',views.UserPost.as_view(),name='for_user'),
    re_path('by/(?P<username>[-\w]+)/(?P<pk>\d+)/', views.PostDetail.as_view(),name='single'),
    re_path('delete/(?P<pk>\d+)/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Simple Social</title>
  <!-- Latest compiled and minified CSS -->

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
  </script>


  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


</head>


<body>


    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Simple Social</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create
                Group</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log
                out</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign
                up</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>




    <div class="container mycontent">

      {% block content %}

      {% endblock %}

    </div>

<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Nikita Kukshynsky</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</body>

</html>

simplesocial/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 style="text-align: center">Welcome to Simple Social</h1>
{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You are now logged in!</h1>
{% endblock content %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visitins, come back soon!</h1>

{% endblock content %}